"""
Imprint — Learning Centre tests
========================================
Type: Content + wiring tests, run headless.

Documentation rots quietly: a page gets renamed, a screenshot is deleted, an
image path is mistyped, and nothing fails — the reader just gets a broken-image
box. These assert the things that would otherwise only be caught by a human
opening the dialog and looking.

The packaging case is the one most likely to bite. The pages live under
`docs/learn/`, which reaches a frozen .app only because Imprint.spec
lists it in `datas`; without that the Learning Centre is empty in the installed
app while working perfectly from source.

Run with:  pytest tests/test_learning_center.py -v
"""

import os
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LEARN_DIR = PROJECT_ROOT / "docs" / "learn"


@pytest.fixture(scope="module")
def app():
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication
    return QApplication.instance() or QApplication([])


def _pages():
    from ui.learning_center import PAGES
    return PAGES


def test_every_listed_page_exists():
    missing = [page.filename for page in _pages()
               if not (LEARN_DIR / page.filename).exists()]
    assert not missing, f"listed in PAGES but not on disk: {missing}"


def test_no_orphan_pages_on_disk():
    """A page nobody can reach is the same as no page."""
    listed = {page.filename for page in _pages()}
    on_disk = {p.name for p in LEARN_DIR.glob("*.md")}
    assert not (on_disk - listed), f"not listed in PAGES: {sorted(on_disk - listed)}"


@pytest.mark.parametrize("filename", [page.filename for page in _pages()])
def test_every_image_reference_resolves(filename):
    """A missing screenshot renders as a broken-image box, not an error."""
    text = (LEARN_DIR / filename).read_text(encoding="utf-8")
    refs = re.findall(r"!\[[^\]]*\]\(([^)]+)\)", text)
    broken = [r for r in refs if not (LEARN_DIR / r).exists()]
    assert not broken, f"{filename} references missing images: {broken}"


@pytest.mark.parametrize("filename", [page.filename for page in _pages()])
def test_internal_links_point_at_real_pages(filename):
    """The pages navigate between themselves by filename."""
    text = (LEARN_DIR / filename).read_text(encoding="utf-8")
    links = re.findall(r"\[[^\]]*\]\(([^)]+\.md)(?:#[^)]*)?\)", text)
    broken = [l for l in links if not (LEARN_DIR / l.split("#")[0]).exists()]
    assert not broken, f"{filename} links to missing pages: {broken}"


@pytest.mark.parametrize("filename", [page.filename for page in _pages()])
def test_pages_render_to_html(filename):
    import markdown
    html = markdown.markdown(
        (LEARN_DIR / filename).read_text(encoding="utf-8"),
        extensions=["tables", "fenced_code", "toc"],
    )
    assert len(html) > 500, f"{filename} rendered suspiciously short"


def test_learn_dir_is_bundled_by_the_spec():
    """Without this line the Learning Centre is empty in the installed .app
    while working perfectly from a source checkout — the kind of break that
    only shows up after shipping."""
    spec = (PROJECT_ROOT / "Imprint.spec").read_text(encoding="utf-8")
    assert '("docs/learn", "docs/learn")' in spec, \
        "docs/learn is not in the PyInstaller datas list"


def test_screenshot_generator_covers_the_referenced_images():
    """The images are generated by scripts/make_learning_shots.py. If a page
    references one the generator does not produce, it cannot be regenerated and
    will go stale the first time the UI changes."""
    generator = (PROJECT_ROOT / "scripts" / "make_learning_shots.py").read_text(encoding="utf-8")
    produced = set(re.findall(r'\("([\w\-]+\.png)"', generator))
    referenced = set()
    for page in _pages():
        text = (LEARN_DIR / page.filename).read_text(encoding="utf-8")
        for ref in re.findall(r"!\[[^\]]*\]\(img/([^)]+)\)", text):
            referenced.add(ref)
    assert referenced <= produced, \
        f"referenced but never generated: {sorted(referenced - produced)}"


def test_dialog_opens_and_lists_the_pages(app, monkeypatch):
    from PySide6.QtWidgets import QDialog
    import main
    from ui import learning_center

    # exec() would block forever with nobody to close it.
    monkeypatch.setattr(QDialog, "exec", lambda self: None)

    window = main.GodAI()
    dialog = learning_center.show_learning_center(window, main.RESOURCE_DIR)

    from PySide6.QtWidgets import QListWidget, QLineEdit, QTextBrowser
    contents = dialog.findChild(QListWidget)
    browser = dialog.findChild(QTextBrowser)
    search = dialog.findChild(QLineEdit, "LearnSearch")
    assert contents is not None and browser is not None
    assert search is not None
    assert contents.count() == len(_pages())
    assert browser.toPlainText().strip(), "first page rendered empty"


def test_search_filters_the_complete_handbook(app, monkeypatch):
    from PySide6.QtCore import Qt
    from PySide6.QtWidgets import QDialog, QLineEdit, QListWidget
    import main
    from ui import learning_center

    monkeypatch.setattr(QDialog, "exec", lambda self: None)
    window = main.GodAI()
    dialog = learning_center.show_learning_center(window, main.RESOURCE_DIR)
    search = dialog.findChild(QLineEdit, "LearnSearch")
    contents = dialog.findChild(QListWidget, "LearnContents")

    search.setText("launcher")
    assert contents.count() == 1
    assert contents.item(0).data(Qt.UserRole) == "07-troubleshooting.md"
    search.clear()
    assert contents.count() == len(_pages())


def test_every_workspace_agent_has_a_learning_guide():
    """Adding a workspace must also add searchable operating guidance."""
    import main

    text = (LEARN_DIR / "02-agents.md").read_text(encoding="utf-8")
    listed = {agent for agents in main.WORKSPACES.values() for agent in agents}
    missing_sections = [agent for agent in listed if f"(`{agent}`)" not in text]
    missing_sheets = [agent for agent in listed
                      if not (PROJECT_ROOT / "docs" / "agents" / f"{agent}.md").exists()]
    assert not missing_sections, f"agents missing Learning Centre section: {missing_sections}"
    assert not missing_sheets, f"agents missing technical guide: {missing_sheets}"


def test_income_page_uses_measured_unit_economics_not_income_forecasts():
    text = (LEARN_DIR / "03-profit.md").read_text(encoding="utf-8").casefold()
    required = (
        "contribution margin", "conversion rate", "human hour",
        "qualified opportunities", "scale rule", "stop rule",
        "observed transaction", "not a forecast",
    )
    assert all(term in text for term in required)
    assert "what to expect, honestly" not in text
    assert "/mo" not in text
    assert "month 6" not in text
